import { Event } from './../models/event';
import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})


export class HttpService {
  events:Event[]=[];
  constructor() {
    for(let i =0; i <100;i++){
      this.events.push({
        id: Math.floor((Math.random()*999999999)+1).toString(),
        class: courses[Math.floor(Math.random()*courses.length)],
        instructor: "Professor "+  names[Math.floor(Math.random()*names.length)],
        duration: Math.floor(Math.random()*59),
        location: locations[Math.floor(Math.random()*locations.length)],
        topic: ["NA", "NA", "NA"],
        date: Math.floor(Math.random() * 3390072 ) + 1555870728 ,
        description: "asdfaf",
        currentCapacity: Math.floor(Math.random()*48),
        maxCapacity: 50,
        organizer: names[Math.floor(Math.random()*names.length)],
        title:titles[Math.floor(Math.random()*titles.length)]
      })
    }
    
    console.log(this.events)
  }

  getPossibleClasses():string[] {
    return courses;
  }

  getRecommandedEvents(values:string[]):Event[]{
    let obj:Event[] = [];

    
    this.events.forEach((event:Event)=>{
      values.forEach((s:string)=>{
        if(event.class.includes(s)){
          obj.push(event)
        }
      })
    })

   obj.sort((a:Event,b:Event)=>{
    return a.date-b.date;
   })
    return obj
  }

  getHappeningSoonEvents ():Event[]{

    return this.events.sort((a:Event,b:Event)=>{
      return a.date-b.date;
     })
  }
  getYourMajorEvents(value:string):Event[]{
    let obj = this.events.filter((event,index)=>{
      return (event.class.includes(value))?event:undefined;
   })
   obj.sort((a:Event,b:Event)=>{
    return a.date-b.date;
   })
    return obj
  }

}


const courses: string[] = [
  "ACCT 201 - Elementary Financial Accounting",
  "ACCT 202 - Managerial Accounting",
  "ACCT 300A - Intermediate Accounting",
  "ACCT 300B - Intermediate Accounting",
  "ACCT 320 - Cost Accounting",
  "ACCT 351 - Federal Tax Law",
  "ACCT 352 - Voluntary Income Tax Assistance (VITA)",
  "ACCT 400 - Advanced Accounting",
  "ACCT 460 - Accountants' Professional Responsibilities and Ethics",
  "ACCT 465 - International Accounting",
  "ACCT 470 - Auditing",
  "ACCT 480 - Accounting Systems and Data Processing",
  "ACCT 493 - Accounting Internships",
  "ACCT 495 - Selected Topics in Accountancy",
  "ACCT 497 - Directed Studies in Accountancy",
  "ACCT 500 - Financial Accounting",
  "ACCT 510 - Intensive Intermediate Accounting I",
  "ACCT 511 - Intensive Intermediate Accounting II",
  "ACCT 512 - Review of Individual Income Taxation",
  "ACCT 513 - Review of Auditing",
  "ACCT 601 - Corporate Governance and Financial Reporting",
  "ACCT 602 - Advanced Cost Accounting",
  "ACCT 603 - Financial Statement Analysis",
  "ACCT 604 - Forensic Accounting",
  "ACCT 605 - Seminar in Accounting Information Systems",
  "ACCT 610 - Managerial Accounting and Control",
  "ACCT 611 - Seminar in Auditing and Assurance Services",
  "ACCT 612 - Governmental and Non-Profit Accounting & Taxation",
  "ACCT 621 - Tax Research and Planning",
  "ACCT 622 - Taxation of Partnerships & S Corporations",
  "ACCT 623 - Taxation of C Corporations and Shareholders",
  "ACCT 631 - Information Systems Governance and Control",
  "ACCT 632 - Information Systems Auditing",
  "ACCT 633 - Accounting Database Systems",
  "ACCT 634 - Advanced Spreadsheet Analysis",
  "ACCT 680 - Financial Reporting and Analysis",
  "ACCT 695 - Selected Topics in Accountancy",
  "ACCT 697 - Directed Studies in Accountancy",
  "ACCT 699 - Accountant's Professional Responsibilities and Ethics",
  "CECS 100 - Critical Thinking in the Digital Information Age",
  "CECS 105 - Introduction to Computer Engineering and Computer Science",
  "CECS 105H - Introduction to Computer Engineering and Computer Science",
  "CECS 110 - Beginning Web Design",
  "CECS 174 - Introduction to Programming and Problem Solving",
  "CECS 200 - Intermediate Web Design",
  "CECS 201 - Computer Logic Design I",
  "CECS 202 - The Digital Information Age",
  "CECS 211 - Principles of Computer Engineering I",
  "CECS 225 - Digital Logic and Assembly Programming",
  "CECS 228 - Discrete Structures with Computing Applications",
  "CECS 228H - Discrete Structures with Computing Applications",
  "CECS 229 - Discrete Structures with Computing Applications II",
  "CECS 229H - Discrete Structures with Computing Applications II",
  "CECS 262 - Introduction to Embedded System Programming",
  "CECS 271 - Introduction to Numerical Methods",
  "CECS 274 - Object Oriented Programming and Data Structures",
  "CECS 274H - Object Oriented Programming and Data Structures",
  "CECS 275 - Programming and Data Structures in C++",
  "CECS 277 - Object Oriented Application Development",
  "CECS 278 - Cyber Security Principles",
  "CECS 282 - C++ for Java Programmers",
  "CECS 282H - C++ for Java Programmers",
  "CECS 300 - Design of Dynamic Web Sites",
  "CECS 301 - Computer Logic Design II",
  "CECS 301H - Computer Logic Design II",
  "CECS 302 - Introduction to Computer Forensics",
  "CECS 303 - Networks and Network Security",
  "CECS 311 - Principles of Computer Engineering II",
  "CECS 323 - Database Fundamentals",
  "CECS 326 - Operating Systems",
  "CECS 327 - Introduction to Networks and Distributed Computing",
  "CECS 327H - Introduction to Networks and Distributed Computing",
  "CECS 328 - Data Structures and Algorithms",
  "CECS 328H - Data Structures and Algorithms",
  "CECS 341 - Computer Architecture and Organization",
  "CECS 343 - Introduction to Software Engineering",
  "CECS 346 - Embedded Systems I",
  "CECS 346H - Embedded Systems I",
  "CECS 347 - Embedded Systems II",
  "CECS 361 - Digital Design Techniques and Verification",
  "CECS 378 - Introduction to Computer Security Principles",
  "CECS 406 - Selected Topics in Computer Science",
  "CECS 410 - Computers and Networks",
  "CECS 412 - Introduction to Computer Network Architectures",
  "CECS 419 - Theory of Computation",
  "CECS 424 - Organization of Programming Languages",
  "CECS 424H - Organization of Programming Languages",
  "CECS 428 - Analysis of Algorithms",
  "CECS 429 - Search Engine Technology",
  "CECS 440 - Computer Architecture",
  "CECS 440H - Computer Architecture",
  "CECS 444 - Compiler Construction",
  "CECS 445 - Software Design and Architecture",
  "CECS 447 - Embedded Systems III",
  "CECS 448 - User Interface Design",
  "CECS 449 - Computer Graphics",
  "CECS 450 - Data Visualization",
  "CECS 451 - Artificial Intelligence",
  "CECS 453 - Mobile Application Development",
  "CECS 455 - Introduction to Game Programming",
  "CECS 456 - Machine Learning",
  "CECS 460 - System on Chip Design",
  "CECS 460H - System on Chip Design",
  "CECS 461 - Hardware/Software Co-design",
  "CECS 463 - Digital Signal Processing Design and Simulation",
  "CECS 470 - Web Programming and Accessibility",
  "CECS 474 - Computer Network Interoperability",
  "CECS 475 - Software Development with Frameworks",
  "CECS 476 - System and Network Administration",
  "CECS 478 - Introduction to Computer Security",
  "CECS 478H - Introduction to Computer Security",
  "CECS 490A - Computer Engineering Senior Project I",
  "CECS 490B - Computer Engineering Senior Project II",
  "CECS 491A - Computer Science Senior Project I",
  "CECS 491B - Computer Science Senior Project II",
  "CECS 495 - Computational Physiology",
  "CECS 496 - Computer Science Problem Solving",
  "CECS 497 - Directed Studies",
  "CECS 519 - Theory of Computation",
  "CECS 521 - Database Architecture",
  "CECS 524 - Advanced Topics in Programming Languages",
  "CECS 526 - Advanced Operating Systems",
  "CECS 528 - Advanced Analysis of Algorithms",
  "CECS 529 - Search Engine Technology",
  "CECS 530 - Advanced Computer Architecture I",
  "CECS 531 - Advanced Computer Architecture II",
  "CECS 532 - Memory Design and Implementation",
  "CECS 542 - Requirements Engineering",
  "CECS 543 - Advanced Software Engineering",
  "CECS 544 - Software Testing and Verification",
  "CECS 545 - Software Architecture",
  "CECS 546 - Fault Tolerant Computing Systems",
  "CECS 547 - Software Maintenance, Reengineering and Reuse",
  "CECS 550 - Pattern Recognition",
  "CECS 551 - Advanced Artificial Intelligence",
  "CECS 552 - Computer Simulation and Modeling",
  "CECS 553 - Machine Vision",
  "CECS 561 - Hardware/Software Co-design",
  "CECS 570 - Concurrent Parallel Programming",
  "CECS 571 - Fundamentals of Semantic Web technologies",
  "CECS 572 - Advanced Computer Networking",
  "CECS 574 - Distributed Computing",
  "CECS 575 - Object-Oriented Analysis and Design",
  "CECS 579 - Information Security",
  "CECS 590 - Selected Topics in Computer Science",
  "CECS 621 - Database Architecture",
  "CECS 624 - Advanced Topics in Programming Languages",
  "CECS 626 - Advanced Operating Systems",
  "CECS 628 - Advanced Analysis of Algorithms",
  "CECS 630 - Advanced Computer Architecture I",
  "CECS 631 - Advanced Computer Architecture II",
  "CECS 643 - Advanced Software Engineering",
  "CECS 644 - Software Testing and Verification",
  "CECS 645 - Software Architecture",
  "CECS 646 - Fault Tolerant Computing Systems",
  "CECS 647 - Software Maintenance, Reengineering and Reuse",
  "CECS 650 - Pattern Recognition",
  "CECS 651 - Advanced Artificial Intelligence",
  "CECS 653 - Machine Vision",
  "CECS 670 - Concurrent Parallel Programming",
  "CECS 672 - Advanced Computer Networking",
  "CECS 674 - Distributed Computing",
  "CECS 675 - Object-Oriented Analysis and Design",
  "CECS 690 - Selected Topics in Computer Science",
  "CECS 694 - Seminar in Computer Science",
  "CECS 697 - Directed Research",
  "CECS 698 - Thesis or Industrial Project",
  "MATH 92 - Foundations for Essential Algebra A",
  "MATH 94 - Foundations for Quantitative Reasoning",
  "MATH 95 - Foundations for Business Calculus",
  "MATH 103 - Mathematical Ideas",
  "MATH 104 - The Power of Mathematics",
  "MATH 109 - Modeling with Algebra",
  "MATH 111 - Precalculus Trigonometry",
  "MATH 112A - Essential Algebra A",
  "MATH 112B - Essential Algebra B",
  "MATH 113 - Precalculus Algebra",
  "MATH 115 - Calculus for Business",
  "MATH 115Z - Calculus for Business",
  "MATH 119A - Survey of Calculus I",
  "MATH 119B - Survey of Calculus II",
  "MATH 122 - Calculus I",
  "MATH 123 - Calculus II",
  "MATH 224 - Calculus III",
  "MATH 233 - Fundamental Concepts for Advanced Mathematics",
  "MATH 247 - Introduction to Linear Algebra",
  "MATH 249 - Linear Algebra and Differential Equations",
  "MATH 297 - Directed Study",
  "MATH 303 - Reflections in Space and Time",
  "MATH 309 - Complexity and Emergence",
  "MATH 310 - History of Early Mathematics",
  "MATH 323 - Introduction to Numerical Analysis",
  "MATH 341 - Number Theory",
  "MATH 347 - Linear Algebra",
  "MATH 349 - Linear Algebra and Differential Equations for Engineers",
  "MATH 355 - College Geometry",
  "MATH 361A - Introduction to Mathematical Analysis I",
  "MATH 361B - Introduction to Mathematical Analysis II",
  "MATH 364A - Ordinary Differential Equations I",
  "MATH 364B - Ordinary Differential Equations II",
  "MATH 370A - Applied Mathematics I",
  "MATH 370B - Applied Mathematics II",
  "MATH 380 - Probability and Statistics",
  "MATH 409 - Strategies for Graduate Admission",
  "MATH 410 - History of Modern Mathematics",
  "MATH 423 - Intermediate Numerical Analysis",
  "MATH 444 - Introduction to Abstract Algebra",
  "MATH 451 - Differential Geometry",
  "MATH 456 - Dynamics and Geometry of Chaos",
  "MATH 461 - Introduction to Complex Analysis",
  "MATH 463 - Multivariable Calculus",
  "MATH 470 - Introduction to Partial Differential Equations",
  "MATH 472 - Fourier Analysis",
  "MATH 473 - Scientific Computing",
  "MATH 474 - Mathematics of Financial Derivatives",
  "MATH 479 - Mathematical Modeling",
  "MATH 485 - Mathematical Optimization",
  "MATH 491 - Honors Seminar in Problem Solving",
  "MATH 495 - Topics in Modern Mathematics",
  "MATH 496 - Special Problems",
  "MATH 497 - Directed Studies",
  "MATH 498H - Senior Thesis - Honors",
  "MATH 520 - Finite Element Method",
  "MATH 521 - Matrix Method in Data Analysis and Pattern Recognition",
  "MATH 540 - Elements of Abstract Algebra",
  "MATH 542 - Algebraic Geometry",
  "MATH 545 - Topics in Abstract Algebra",
  "MATH 550 - Elements of Topology",
  "MATH 555 - Topics in Topology",
  "MATH 560 - Functional Analysis",
  "MATH 561 - Elements of Real Analysis",
  "MATH 562 - Elements of Complex Analysis",
  "MATH 563 - Applied Analysis",
  "MATH 564 - Applied Nonlinear Ordinary Differential Equations",
  "MATH 565 - Topics in Real Analysis",
  "MATH 566 - Topics in Complex Analysis",
  "MATH 570 - Partial Differential Equations",
  "MATH 573 - Advanced Scientific Computing",
  "MATH 574 - Stochastic Calculus and Applications",
  "MATH 575 - Calculus of Variations",
  "MATH 576 - Numerical Analysis",
  "MATH 577 - Numerical Solution of Partial Differential Equations",
  "MATH 578 - Numerical Linear Algebra",
  "MATH 579 - Advanced Mathematical Modeling",
  "MATH 590 - Selected Topics in Mathematics",
  "MATH 680 - Topics in Ordinary Differential Equations",
  "MATH 681 - Topics in Partial Differential Equations",
  "MATH 682 - Topics in Numerical Analysis",
  "MATH 695 - Seminar in Mathematics",
  "MATH 697 - Directed Studies",
  "MATH 698 - Thesis or Project",
  "PHYS 100A - General Physics",
  "PHYS 100B - General Physics",
  "PHYS 151 - Mechanics and Heat",
  "PHYS 152 - Electricity and Magnetism",
  "PHYS 254 - Applied Modern Physics",
  "PHYS 255 - Laboratory on Modern Physics",
  "PHYS 310 - Analytical Mechanics",
  "PHYS 320 - Thermodynamics",
  "PHYS 340A - Electricity and Magnetism I",
  "PHYS 340B - Electricity and Magnetism II",
  "PHYS 350 - Quantum Physics I",
  "PHYS 360 - Physics With Symbolic Algebra Software",
  "PHYS 380 - Electronics",
  "PHYS 385 - Materials Science",
  "PHYS 385C - Materials Science Colloquium",
  "PHYS 385L - Materials Science Laboratory",
  "PHYS 390 - Exploring Physics Teaching",
  "PHYS 410 - Relativity",
  "PHYS 422 - Statistical Physics",
  "PHYS 434 - Astrophysics",
  "PHYS 445 - Advanced Experimental Methods in Materials Science",
  "PHYS 446 - Advanced Experimental Methods in Physical and Electronic Properties",
  "PHYS 447 - Advanced Experimental Methods in Nanoscale Physics",
  "PHYS 450 - Quantum Physics II",
  "PHYS 465 - Polymer Physics / Polymer Physical Chemistry",
  "PHYS 466 - Biophysics",
  "PHYS 470 - Introduction to Solid State Physics",
  "PHYS 476 - Modern Optics with Laboratory",
  "PHYS 480 - Computer Interfacing in Experimental Physics",
  "PHYS 490 - Selected Topics in Physics",
  "PHYS 491A - Pedagogical Content Knowledge in Physics - Force and Motion",
  "PHYS 491B - Pedagogical Content Knowledge in Physics - Energ and Momentum",
  "PHYS 491C - Pedagogical Content Knowledge in Physics - Waves and Optics",
  "PHYS 491D - Pedagogical Content Knowledge in Physics - Electrcity and Magnetism",
  "PHYS 491E - Pedagogical Content Knowledge in Physics - Nuclear and Thermal",
  "PHYS 495 - Colloquium",
  "PHYS 496 - Special Problems in Physics",
  "PHYS 510 - Graduate Mechanics",
  "PHYS 515 - Relativity",
  "PHYS 522 - Statistical Physics",
  "PHYS 534 - Astrophysics",
  "PHYS 540A - Graduate Electrodynamics",
  "PHYS 545 - Advanced Experimental Methods in Material Science",
  "PHYS 546 - Advanced Experimental Methods in Physical and Electronic Properties",
  "PHYS 547 - Advanced Experimental Methods in Nanoscale Physics",
  "PHYS 550A - Quantum Mechanics I",
  "PHYS 550B - Quantum Mechanics II",
  "PHYS 554 - Nuclear Physics",
  "PHYS 555 - Elementary Particle Physics",
  "PHYS 560A - Mathematical Methods of Physics",
  "PHYS 562 - Advanced Computational Methods in Physics",
  "PHYS 565 - Polymer Physics / Polymer Physical Chemistry",
  "PHYS 566 - Biophysics",
  "PHYS 569 - Introduction to Solid State Physics",
  "PHYS 576 - Modern Optics with Laboratory",
  "PHYS 580 - Computer Interfacing in Experimental Physics",
  "PHYS 590 - Selected Topics in Physics",
  "PHYS 595 - Colloquium",
  "PHYS 691 - Directed Study",
  "PHYS 692 - Professional Physics Internship",
  "PHYS 694 - Seminar in Special Topics",
  "PHYS 695 - Colloquium",
  "PHYS 697 - Directed Research",
  "PHYS 698 - Thesis",
  "PHYS 699 - Professional Project",
  "KOR 101 - Fundamentals of Korean",
  "KOR 102 - Fundamentals of Korean",
  "KOR 201 - Intermediate Korean",
  "KOR 202 - Intermediate Korean",
  "CEM 121 - Construction Drawing I",
  "CEM 125 - Fundamentals of Construction",
  "CEM 200 - Concrete Construction",
  "CEM 200L - Concrete Construction Laboratory",
  "CEM 202 - Probability and Statistics for Construction Engineering Management",
  "CEM 204 - Applied Mechanics-Statics",
  "CEM 206 - Trends in Construction Engineering Management",
  "CEM 225 - Residential and Light Commercial Construction Practices and Estimating",
  "CEM 304 - Applied Mechanics Strength of Materials",
  "CEM 310 - Communication in Engineering Profession",
  "CEM 315 - Construction Safety",
  "CEM 320 - Operations Management in Contemporary Organizations",
  "CEM 324 - Commercial, Institutional and Industrial Construction Practices and Estimating",
  "CEM 335 - Soil Mechanics Technology",
  "CEM 335L - Soil Mechanics Technology Laboratory",
  "CEM 365 - Mechanical Equipment for Buildings",
  "CEM 373 - Fundamentals of Integrated Project Delivery",
  "CEM 375 - Electrical Equipment for Buildings",
  "CEM 405 - Construction Management Problem Solving",
  "CEM 409 - Directed Studies in Construction Engineering Management",
  "CEM 421 - Construction Planning and Scheduling",
  "CEM 424 - Earthwork and Civil Works Construction Practices",
  "CEM 426 - Business and Construction Law",
  "CEM 429 - Advanced Estimating and Bidding",
  "CEM 432 - Facility Administration",
  "CEM 433 - Facility Finance Management",
  "CEM 434 - Facility and Property Management",
  "CEM 436 - Facility Operations Management",
  "CEM 437 - Structural Building Systems",
  "CEM 476 - Construction and Maintenance of Infrastructure Facilities",
  "CEM 481 - Sustainability in the Built Environment",
  "CEM 485 - CEM Senior Seminar",
  "CEM 486 - Infrastructure Management",
  "CEM 490 - Construction Project Management",
  "ART 101 - Artists in Their Own Words",
  "ART 110 - Introduction to the Visual Arts",
  "ART 121 - Safety and Sustainable Practices for Studio Artists",
  "ART 130 - Foundation Two-Dimensional",
  "ART 131 - Foundation Three Dimensional",
  "ART 132 - Foundation Color Theory",
  "ART 149 - Foundation Computer Art",
  "ART 150 - Foundation Transdisciplinary Practice",
  "ART 181 - Foundation Drawing",
  "ART 184 - Foundation Life Drawing",
  "ART 221 - Shop Orientation",
  "ART 223 - Introduction to Typography",
  "ART 227 - History of Animation",
  "ART 241 - Introduction to Photography",
  "ART 251A - Introduction to Ceramics: Handbuilding",
  "ART 251B - Introduction to Ceramics: Wheel Throwing",
  "ART 254 - Introduction to Wood",
  "ART 257 - Introduction to Metals",
  "ART 261 - Introduction to Life Sculpture: From the Figure to the Body",
  "ART 263 - Introduction to Sculpture/4D",
  "ART 265 - Introduction to Fiber",
  "ART 270 - Introduction to Printmaking",
  "ART 271 - Introduction to Rendering",
  "ART 272 - Drawing With Perspective",
  "ART 287 - Introduction to Painting",
  "ART 291 - Introduction to Animation",
  "ART 300 - Art, Adolescence, and the Child",
  "ART 305 - Art Disciplines and New Technology",
  "ART 311 - Writing about Visual Art",
  "ART 316 - Fiber: Pattern Design and Printing",
  "ART 317 - Fiber: Textile Dyeing",
  "ART 318 - TYPE II: Intermediate Typography",
  "ART 321 - Graphic Design I: Introduction to Graphic Design",
  "ART 327 - Graphic Design II: Intermediate Graphic Design",
  "ART 328A - Fiber and Mixed Media: Sculptural Forms",
  "ART 328B - Fiber and Mixed Media: Sculptural Forms",
  "ART 331 - Advertising I: Introduction to Concept Development",
  "ART 332 - Graphic Design: Professional Preparation",
  "ART 333 - Global Art Scenes",
  "ART 334 - Graphic Design III: Exploration and Experimentation",
  "ART 335 - Advertising II: Intermediate Concept Development and Art Direction",
  "ART 336 - Graphic Design IV: Development and Analysis",
  "ART 337 - Graphic Design V: Packaging Design",
  "ART 340 - Intermediate Photography",
  "ART 341A - Intermediate Ceramics: Handbuilding",
  "ART 341B - Intermediate Ceramics: Wheel Throwing",
  "ART 342A - Contemporary Practices in Color Photography",
  "ART 343A - Ceramics Sculpture",
  "ART 343B - Advanced Wheel Throwing",
  "ART 349 - Computer Art",
  "ART 352A - Ceramics: Glaze Technology",
  "ART 352B - Ceramics: Plaster and Alternative Practices",
  "ART 353A - Drafting and Model Making for 3D Art Objects",
  "ART 353B - Digital Furniture Design and Production",
  "ART 354A - Furniture Making: Joinery and Structure",
  "ART 354B - Furniture Making: Bending, Forming and Sculpting",
  "ART 354C - Furniture Making: Casework",
  "ART 355 - Enameling",
  "ART 356 - Jewelry Casting",
  "ART 357A - Metals and Jewelry",
  "ART 357B - Metal and Jewelry Design",
  "ART 358A - Metalsmithing",
  "ART 358B - Intermediate Metalsmithing",
  "ART 359A - Architectural Metalwork and Blacksmithing",
  "ART 359B - Sculptural Metalwork",
  "ART 360A - Sculpture/4D: Intermediate",
  "ART 360B - Sculpture/4D: Intermediate",
  "ART 361 - Sculpture/4D: Observation",
  "ART 363A - Sculpture/4D: Fabrication Lab A",
  "ART 363B - Sculpture/4D: Fabrication Lab B",
  "ART 363C - Digital Fabrication Lab",
  "ART 364 - Sculpture/4D: Electronics, Mechanics, Kinetics",
  "ART 365 - Media Design: Motion Graphics",
  "ART 366 - Media Design: User-Centered Design",
  "ART 367A - Sculpture/4D: Mold Making Lab",
  "ART 367B - Bronze and Metal Casting: Foundry Lab",
  "ART 369 - Axis: Woodturning and Metal Spinning",
  "ART 370 - Printmaking",
  "ART 371A - Illustration 1",
  "ART 371B - Illustration 2",
  "ART 372 - Anatomy for Artists",
  "ART 373 - Costumed Figure Drawing",
  "ART 374A - Biomedical Rendering",
  "ART 374B - Biomedical Illustration",
  "ART 375 - Art and Social Action: A Global Perspective",
  "ART 376 - Printmaking: Relief Printing",
  "ART 377 - Printmaking: Silkscreen",
  "ART 378 - Printmaking: Etching",
  "ART 379 - Printmaking: Lithography",
  "ART 381 - Intermediate Drawing",
  "ART 382 - Production for Fine Art",
  "ART 383 - Life Painting",
  "ART 384 - Intermediate Life Drawing",
  "ART 385 - Watercolor Painting",
  "ART 387 - Painting",
  "ART 388 - Advanced Studies in Color",
  "ART 389 - Materials and Techniques of Drawing and Painting",
  "ART 390 - Drawing: Figures in Context",
  "ART 391 - Animation 1",
  "ART 392 - Animation 2",
  "ART 393 - Character Design",
  "ART 394 - Professional Practices in Illustration/Animation",
  "ART 401 - Cross-cultural and Community-based Practices in Art",
  "ART 406A - Digital Imagery for the Arts",
  "ART 406B - Advanced Digital Imagery for the Arts",
  "ART 407 - Materials and Methods for K-12 Classrooms",
  "ART 408 - Perspectives in Contemporary Art Education",
  "ART 409 - Educational Practices in the Art Museum",
  "ART 412 - Aesthetic Theories and Art Education",
  "ART 414 - Documentary Photography",
  "ART 415 - On-Site Studies in Art Education",
  "ART 416 - Animation 3",
  "ART 417 - Animation 4",
  "ART 418 - Visual Development",
  "ART 419 - Media Design: 5D; Designing the Future",
  "ART 420 - Graphic Design Workshop",
  "ART 421 - Advanced Typography",
  "ART 423 - Graphic Design VI: Advanced Topics",
  "ART 424 - Advertising III: Advanced Topics",
  "ART 426 - Computer Animation 1",
  "ART 427 - Computer Animation 2",
  "ART 428A - Fiber: Weaving, Dyeing, Woven Structures",
  "ART 428B - Fiber: Weaving, Dyeing, Woven Structures",
  "ART 430 - Fiber: Artist Books and Papermaking",
  "ART 432 - Fiber and Mixed Media: Advanced",
  "ART 436A - Sculpture/4D: Video Art",
  "ART 436B - Sculpture/4D: Video Art",
  "ART 440 - Art in Public Places: Theory and Practice",
  "ART 442 - Internship in Graphic Design",
  "ART 444 - Advanced Black and White Photography",
  "ART 447A - Photography Studio Specialties",
  "ART 447B - Advanced Studio Lighting",
  "ART 448 - The Moving Image",
  "ART 449 - Experimental Practices in Photography",
  "ART 450A - Installation Concepts and New Genres",
  "ART 450B - Installation Concepts and New Media",
  "ART 451A - Advanced Ceramics",
  "ART 451B - Advanced Ceramics",
  "ART 453 - Seminar in Ceramic Arts",
  "ART 454A - Advanced Furniture Making: Shelter, Architecture and Advanced Joinery Systems",
  "ART 454B - Advanced Furniture Making: Upholstery and New Materials",
  "ART 458A - Advanced Metalsmithing/ Jewelry and Enameling",
  "ART 458B - Advanced Metalsmithing/ Jewelry and Enameling",
  "ART 460A - Advanced Sculpture Critique 1",
  "ART 460B - Advanced Sculpture Critique 2",
  "ART 471A - Illustration 3",
  "ART 471B - Illustration 4",
  "ART 472 - Storyboarding for Film and Television",
  "ART 473 - Seminar in Photo-Based Art",
  "ART 474 - Seminar in Sculpture and Time-Based Art",
  "ART 475 - Printmaking: Photo and Digital Processes",
  "ART 476 - Experimental Animation 1",
  "ART 478 - Experimental Animation 2",
  "ART 480 - Printmaking: Monotype/Monoprint",
  "ART 481 - Advanced Drawing",
  "ART 482 - Sequential Imagery",
  "ART 483 - Advanced Life Painting",
  "ART 484 - Advanced Life Drawing",
  "ART 487 - Advanced Painting",
  "ART 489 - Selected Topics in Visual Art",
  "ART 490 - Selected Topics in Studio Art",
  "ART 491A - Ceramics: BFA Culminating Project",
  "ART 491B - 3-D Media-Senior Project",
  "ART 491C - Photography - Senior Project",
  "ART 491E - Illustration/Animation Senior Project",
  "ART 491F - Sculpture/4D Senior Project",
  "ART 491G - Drawing and Painting: Senior Project",
  "ART 491P - Printmaking: Senior Project",
  "ART 492F - Concentrated Studies in Life Drawing",
  "ART 492G - Concentrated Studies in Abstract Painting",
  "ART 492Z - Concentrated Studies in Life Painting",
  "ART 495 - Field Studies in Art",
  "ART 496A - BFA Capstone: Drawing and Painting",
  "ART 496B - BFA Capstone: Drawing and Painting",
  "ART 499A - Special Studies in Ceramics",
  "ART 499B - Special Studies in Wood",
  "ART 499D - Special Studies in Drawing",
  "ART 499E - Special Studies in Animation",
  "ART 499F - Special Studies in Illustration",
  "ART 499J - Special Studies in Metalsmithing and Jewelry",
  "ART 499K - Special Studies in Painting",
  "ART 499M - Special Studies in Life Sculpture",
  "ART 499N - Special Studies in Fiber and Mixed Media",
  "ART 499O - Special Studies in Sculpture/4D",
  "ART 499P - Special Studies in Art Education",
  "ART 499R - Special Studies in Printmaking",
  "ART 499S - Special Studies in Graphic Design",
  "ART 499V - Special Studies in Art Photography",
  "ART 501 - Cross-cultural and Community-based Practices in Art",
  "ART 506A - Digital Imagery for the Arts",
  "ART 506B - Advanced Digital Imagery for the Arts",
  "ART 508 - Perspectives in Contemporary Art Education",
  "ART 509 - Educational Practices in the Art Museum",
  "ART 509A - Research in Art Education",
  "ART 509B - Research in Art Education",
  "ART 512 - Aesthetic Theories and Art Education",
  "ART 514 - Documentary Photography",
  "ART 516 - Animation 3",
  "ART 517 - Animation 4",
  "ART 519 - Media Design: 5D; Designing the Future",
  "ART 526 - Computer Animation 1",
  "ART 527 - Computer Animation 2",
  "ART 536A - Sculpture/4D: Video Art",
  "ART 536B - Sculpture/4D: Video Art",
  "ART 540 - Art in Public Places: Theory and Practice",
  "ART 544 - Fine Print Photography",
  "ART 547A - Photography Studio Specialties",
  "ART 547B - Advanced Studio Lighting",
  "ART 549 - Experimental Practices in Photography",
  "ART 550 - Sculpture/4D: Intermedia/New Genres/New Media",
  "ART 551A - Advanced Ceramics - Graduate",
  "ART 551B - Advanced Ceramics - Graduate",
  "ART 554A - Wood - Graduate",
  "ART 554B - Wood - Graduate",
  "ART 558A - Metalsmithing, Jewelry and Enameling",
  "ART 558B - Metalsmithing, Jewelry and Enameling",
  "ART 572 - Storyboarding for Film and Television",
  "ART 573 - Seminar in Photo-Based Art",
  "ART 574 - Seminar in Sculpture and Time-Based Art",
  "ART 575 - Printmaking: Photo and Digital Processes",
  "ART 576 - Experimental Animation 1",
  "ART 578 - Experimental Animation 2",
  "ART 580 - Printmaking: Monotype/Monoprint",
  "ART 582 - Sequential Imagery",
  "ART 583 - Advanced Life Graduate Painting",
  "ART 589 - Selected Topics in Visual Art",
  "ART 590 - Selected Topics in Studio Art",
  "ART 592Z - Graduate Concentrated Studies in Life Painting",
  "ART 597A - Graduate Studies: Ceramics",
  "ART 597B - Graduate Studies: Wood",
  "ART 597D - Graduate Studies Drawing and Painting",
  "ART 597F - Graduate Studies: Illustration/Animation",
  "ART 597J - Graduate Studies: Metal",
  "ART 597K - Graduate Studies: Painting",
  "ART 597L - Graduate Studies: Life Drawing and Painting",
  "ART 597N - Graduate Studies: Fiber",
  "ART 597O - Graduate Studies: Sculpture/4D",
  "ART 597R - Graduate Studies: Printmaking",
  "ART 597S - Graduate Studies: Visual Communication Design",
  "ART 597V - Graduate Studies: Photography",
  "ART 598A - Graduate Studies: Advanced Ceramics",
  "ART 598B - Graduate Studies: Advanced Wood",
  "ART 598D - Graduate Studies: Advanced Drawing",
  "ART 598F - Graduate Studies: Advanced Illustration/Animation",
  "ART 598J - Graduate Studies: Advanced Metal",
  "ART 598K - Graduate Studies: Advanced Painting",
  "ART 598L - Graduate Studies: Advanced Life Drawing and Painting",
  "ART 598N - Graduate Studies: Advanced Fiber",
  "ART 598O - Graduate Studies: Advanced Sculpture/4D",
  "ART 598R - Graduate Studies: Advanced Printmaking",
  "ART 598S - Graduate Studies: Advanced Visual Communication Design",
  "ART 598V - Graduate Studies: Advanced Photography",
  "ART 601A - Seminar in Art Education",
  "ART 601B - Seminar in Art Education",
  "ART 651 - Seminar in Ceramic Art",
  "ART 680 - Graduate Interdisciplinary Critique",
  "ART 681 - Graduate Studies: Art Theory/Criticism",
  "ART 682 - Graduate Studies: Professional Practices for Studio Art",
  "ART 683 - Graduate Studies: Image as Text",
  "ART 684 - Graduate Studies: Professional Practices for Visual Communication",
  "ART 685 - Writing for Artists",
  "ART 690M - 3-D Graduate Seminar",
  "ART 692 - Project Exhibition",
  "ART 693 - Teaching Internship",
  "ART 694 - Graduate Studies: Directed Studio",
  "ART 695 - Graduate Studies: Field Problems",
  "ART 697 - Graduate Studies: Directed",
  "ART 698A - Art Education Thesis or Project",
  "ART 698B - Studio Project",
  "ART 699 - Graduate Studies: MFA Project",
  "KHMR 101 - Fundamentals of Khmer",
  "KHMR 102 - Fundamentals of Khmer",
  "KHMR 201 - Intermediate Khmer",
  "BIOL 101 - Introduction to Human Disease",
  "BIOL 153 - Introduction to Marine Biology",
  "BIOL 153L - Introduction to Marine Biology Laboratory",
  "BIOL 200 - General Biology",
  "BIOL 200L - General Biology Laboratory",
  "BIOL 201 - General Microbiology for Health Professionals",
  "BIOL 205 - Human Biology",
  "BIOL 205L - Human Biology Laboratory",
  "BIOL 207 - Human Physiology",
  "BIOL 208 - Human Anatomy",
  "BIOL 211 - Introduction to Evolution and Diversity",
  "BIOL 211L - Introduction to Evolution and Diversity Laboratory",
  "BIOL 212 - Introduction to Cell and Molecular Biology",
  "BIOL 212L - Introduction to Cell and Molecular Biology Laboratory",
  "BIOL 213 - Introduction to Ecology and Physiology",
  "BIOL 213L - Introduction to Ecology and Physiology Laboratory",
  "BIOL 260 - Biostatistics",
  "BIOL 296 - Introduction to Undergraduate Directed Research",
  "BIOL 300 - Human Immunology: In Self-Defense",
  "BIOL 301 - Biology of Human Aging",
  "BIOL 311 - General Microbiology",
  "BIOL 312 - Evolutionary Biology",
  "BIOL 313 - Invertebrate Zoology",
  "BIOL 316 - General Entomology",
  "BIOL 320 - Bacterial Pathogenesis",
  "BIOL 320L - Bacterial Pathogenesis Laboratory",
  "BIOL 322 - Medical Mycology/Parasitology",
  "BIOL 324 - Vertebrate Zoology",
  "BIOL 325 - Emerging Infectious Diseases",
  "BIOL 340 - Molecular Cell Biology",
  "BIOL 342 - Human/Mammalian Physiology",
  "BIOL 342L - Laboratory in Human/Mammalian Physiology",
  "BIOL 345 - Comparative Animal Physiology",
  "BIOL 345L - Laboratory in Comparative Animal Physiology",
  "BIOL 350 - General Ecology",
  "BIOL 353 - Marine Biology",
  "BIOL 355 - Microbial Ecology",
  "BIOL 355L - Microbial Ecology Laboratory",
  "BIOL 370 - General Genetics",
  "BIOL 371 - Microbial Genetics",
  "BIOL 372 - Methods in Microbial Genetics",
  "BIOL 411 - Marine Mammalogy",
  "BIOL 412 - Advanced Evolutionary Biology",
  "BIOL 415 - Marine Microbiology",
  "BIOL 416 - Virology",
  "BIOL 419 - Ichthyology",
  "BIOL 420 - Fisheries Ecology and Conservation",
  "BIOL 421 - Herpetology",
  "BIOL 423 - Mammalogy",
  "BIOL 424 - Ornithology",
  "BIOL 425 - Phycology",
  "BIOL 427 - Vascular Plant Systematics",
  "BIOL 429 - Epidemiology of Infectious Diseases",
  "BIOL 430 - Immunology",
  "BIOL 431 - Biology of Cancer",
  "BIOL 432 - Stem Cell Biology",
  "BIOL 433 - Developmental Biology",
  "BIOL 434 - Hematology",
  "BIOL 435 - Pharmacology and Toxicology",
  "BIOL 439 - Plant Morphology",
  "BIOL 440L - Molecular Cell Biology Laboratory",
  "BIOL 442 - Physiology at the Limit",
  "BIOL 443 - Endocrinology",
  "BIOL 444 - Reproductive Biology",
  "BIOL 447 - Molecular Plant Physiology",
  "BIOL 448 - Principles of Neurobiology",
  "BIOL 450 - Plant Ecology",
  "BIOL 451 - Wetlands and Mangrove Ecology",
  "BIOL 452 - Behavioral Ecology",
  "BIOL 454A - Research in Tropical Marine Ecology",
  "BIOL 454B - Research in Tropical Terrestrial Ecology",
  "BIOL 455 - Ecology of Marine Communities",
  "BIOL 456 - Population Ecology",
  "BIOL 457 - Field Methods in Ecology",
  "BIOL 459 - Conservation Biology",
  "BIOL 462 - Bioethics and Public Policy",
  "BIOL 464 - Aquatic Toxicology",
  "BIOL 465 - Experimental Design and Regression Analysis",
  "BIOL 467 - Multivariate Data Analysis",
  "BIOL 471 - Bacterial Physiology",
  "BIOL 472 - Molecular Evolution",
  "BIOL 473 - Molecular Genetics",
  "BIOL 474 - Bioinformatics",
  "BIOL 477 - Biotechnology: Applications of Molecular Techniques and Bioinformatics",
  "BIOL 480 - Seminars",
  "BIOL 490 - Selected Topics in Biology",
  "BIOL 490L - Selected Topics in Biology, Laboratory",
  "BIOL 492A - Stem Cell Research Internship",
  "BIOL 495 - Instruction in Laboratory Teaching",
  "BIOL 496 - Undergraduate Directed Research",
  "BIOL 511 - Marine Mammalogy",
  "BIOL 515 - Marine Microbiology",
  "BIOL 516 - Virology",
  "BIOL 520 - Fisheries Ecology and Conservation",
  "BIOL 524 - Ornithology",
  "BIOL 529 - Epidemiology of Infectious Diseases",
  "BIOL 531 - Biology of Cancer",
  "BIOL 532 - Stem Cell Biology",
  "BIOL 533 - Developmental Biology",
  "BIOL 534 - Hematology",
  "BIOL 535 - Pharmacology and Toxicology",
  "BIOL 540 - Advanced Molecular Cell Biology and Physiology",
  "BIOL 542 - Physiology at the Limit",
  "BIOL 543 - Endocrinology",
  "BIOL 544 - Reproductive Biology",
  "BIOL 548 - Principles of Neurobiology",
  "BIOL 550 - Plant Ecology",
  "BIOL 551 - Wetlands and Mangrove Ecology",
  "BIOL 552 - Behavioral Ecology",
  "BIOL 554A - Research in Tropical Marine Ecology",
  "BIOL 554B - Research in Tropical Terrestrial Ecology",
  "BIOL 555 - Ecology of Marine Communities",
  "BIOL 556 - Population Ecology",
  "BIOL 557 - Field Methods in Ecology",
  "BIOL 559 - Conservation Biology",
  "BIOL 562 - Bioethics and Public Policy",
  "BIOL 563 - Computer Modeling in Biology",
  "BIOL 564 - Aquatic Toxicology",
  "BIOL 565 - Experimental Design and Regression Analysis",
  "BIOL 567 - Multivariate Data Analysis",
  "BIOL 571 - Bacterial Physiology",
  "BIOL 572 - Molecular Evolution",
  "BIOL 573 - Molecular Genetics",
  "BIOL 574 - Bioinformatics",
  "BIOL 577 - Biotechnology: Applications of Molecular Techniques and Bioinformatics",
  "BIOL 580 - Seminars",
  "BIOL 590 - Selected Topics in Biology",
  "BIOL 590L - Selected Topics in Biology, Laboratory",
  "BIOL 592A - Stem Cell Research Internship",
  "BIOL 661 - Seminar in Microbiology",
  "BIOL 663 - Seminar in Cell and Molecular Biology",
  "BIOL 664 - Seminar in Marine Biology",
  "BIOL 665 - Seminar in Ecology",
  "BIOL 666 - Seminar in Physiology",
  "BIOL 696A - Research Design and Ethics",
  "BIOL 696B - Scientific Communication",
  "BIOL 697 - Directed Research",
  "BIOL 698 - Thesis"]

const locations=["49er Pool	POOL",
"49er Softball Complex	SC",
"Academic Services 	AS",
"Barrett Athletic Administration Center	BAC",
"Bookstore 	BKS",
"Brotman Hall 	BH",
"Carpenter Performing Arts Center 	CPAC",
"Central Plant 	CP",
"College of Business Administration 	CBA",
"Child Development Center",
"Corporation Yard",
"Dance Center",
"Design",
"Education 1",
"Education 2",
"Engineering 2",
"Engineering 3",
"Engineering 4",
"Engineering/Computer Sciences",
"Engineering Technology",
"Facilities Management",
"Faculty Office 2",
"Faculty Office 3",
"Faculty Office 4",
"Faculty Office 5",
"Family & Consumer Sciences",
"Fine Arts 1",
"Fine Arts 2",
"Fine Arts 3",
"Fine Arts 4",
"Foundation",
"Hall of Science",
"Health & Human Services 1 Classrooms",
"Health & Human Services 2 Offices",
"Horn Center",
"Housing & Residential Life",
"Human Services and Design",
"Japanese Garden",
"Kinesology",
"KKJZ/FM",
"Language Arts Building",
"Lecture Halls 150/151",
"Liberal Arts 1",
"Liberal Arts 2",
"Liberal Arts 3",
"Liberal Arts 4",
"Liberal Arts 5",
"Library",
"Mail Services",
"McIntosh Humanities Bldg",
"Microbiology",
"Mike & Arline Walter Pyramid",
"Molecular & Life Sciences Center",
"Multi-Media Center",
"Nursing",
"Outdoor Beach Course",
"Outpost Food Service",
"Parking and Transportation Svc",
"Peterson Hall 1",
"Peterson Hall 2",
"Psychology",
"Receiving",
"Recycling Center",
"International House",
"Los Alamitos Hall",
"Los Cerritos Hall",
"Residence Commons and Housing",
"Parkside Commons and Housing",
"Social Sciences / Public Administration",
"Soroptomist House",
"Student Health Services",
"Student Recreation I Wellness Center",
"Tennis Center",
"Theater Arts",
"University Art Museum",
"University Bookstore",
"University Dining Plaza",
"University Music Center",
"University Police Department",
"University Print Shop",
"University Student Union",
"University Telecommunications",
"Visitor Information Center",
"Vivian Engineering Center "]

const names=["Jeremiah",
"Sheridan",
"Madge",
"Chelsey",
"Erik",
"Eleonora",
"Cherise",
"Tempie",
"Bobbie",
"Iluminada",
"Felica",
"Tod",
"Celia",
"Octavio",
"Tifany",
"Raphael",
"Valarie",
"Marielle",
"Quinton",
"Angelyn",
"Salley",
"Lakita",
"Anette",
"Jared",
"Dusti",
"Adina",
"Lynne",
"Janita",
"Shana",
"Domenica",
"Jann",
"Iva",
"Gia",
"Lindsay",
"Tarah",
"Alleen",
"Hunter",
"Gerardo",
"Reginald",
"Robbi",
"Oralee",
"Deetta",
"Madonna",
"Ivan",
"Barbie",
"Latoria",
"Kandace",
"Krissy",
"Buford",
"Len"
]

const titles =["Looking for help in Machine Learning",
"Chemistry Semester Group Study ",
"Need help with Artifical Intelligence",
"Need Help Taking Derivatives",
"Looking for Help in A.I.",
"Need Help in Maching Learning",
"Who can help me with Matlab",
"Anyone free to study for Biology?",
"Who wants to study for Algorithms quiz?",
"Can anyone proof read my paper?",
"Looking for a group to study for Midterm",
"Who's available to study for Linguistics?",
"Does anyone know their integrals?",
"I need help with limits?",
"Does anyone have experience with Python?",
"Does anyone know about nodeJS?",
"Who can meet up to review the labs?",
"Interested in Book Club?",
"Group Study for Anatomy",
"Group Study for Physics",
"Who knows Fluid Dynamics?",
"Who knows circuits?",
"Lets study for Psychology",
"I need help with aerodynamics",
"Lets get HW done for Chemistry?",
"Looking for help in Machine Learning",
"Chemistry Semester Group Study ",
"Need help with Artifical Intelligence",
"Need Help Taking Derivatives",
"Looking for Help in A.I.",
"Need Help in Maching Learning",
"Who can help me with Matlab",
"Anyone free to study for Biology?",
"Who wants to study for Algorithms quiz?",
"Can anyone proof read my paper?",
"Looking for a group to study for Midterm",
"Who's available to study for Linguistics?",
"Does anyone know their integrals?",
"I need help with limits?",
"Does anyone have experience with Python?",
"Does anyone know about nodeJS?",
"Who can meet up to review the labs?",
"Interested in Book Club?",
"Group Study for Anatomy",
"Group Study for Physics",
"Who knows Fluid Dynamics?",
"Who knows circuits?",
"Lets study for Psychology",
"I need help with aerodynamics",
"Lets get HW done for Chemistry?"]
// const events:Event[]=[
//   {
//     id: Math.floor((Math.random()*999999999)+1).toString(),
//     class: courses[Math.random()*courses.length],
//     instructor: "Professor "+  names[Math.random()*names.length],
//     duration: Math.random()*59,
//     location: locations[Math.random()*locations.length],
//     topic: ["NA", "NA", "NA"],
//     date: Math.floor(Math.random() * 3390072 ) + 1555870728 ,
//     description: "asdfaf",
//     currentCapacity: Math.random()*48,
//     maxCapacity: 50,
//     organizer: names[Math.random()*names.length],
//     title:"TTTTTT-1"
//   }
// ]